# Generated by Django 4.0.4 on 2022-05-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_test',
            field=models.ManyToManyField(blank=True, to='quiz.test', verbose_name='Created test'),
        ),
    ]
