# Generated by Django 4.0.4 on 2022-05-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_profile_created_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Test description'),
        ),
    ]
