# Generated by Django 4.0.4 on 2022-05-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_answer_test_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='test',
        ),
    ]
