# Generated by Django 4.0.4 on 2022-05-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Test description'),
        ),
    ]
