# Generated by Django 4.0.4 on 2022-05-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_result_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='completed_by_user',
            field=models.ManyToManyField(blank=True, to='quiz.profile', verbose_name='Completed by'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(blank=True, to='quiz.answer', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.ManyToManyField(blank=True, to='quiz.answer', verbose_name='Answer'),
        ),
    ]
