# Generated by Django 4.0.4 on 2022-05-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_test_completed_by_user_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
    ]
