# Generated by Django 4.0.4 on 2022-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_test_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=255, verbose_name='Rank')),
                ('value', models.IntegerField(verbose_name='Value')),
            ],
        ),
    ]
